-- AlterTable
ALTER TABLE "PlayerStats" ALTER COLUMN "beers" SET DEFAULT 0,
ALTER COLUMN "beers" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PlayerStatsLifetime" ALTER COLUMN "beers" SET DEFAULT 0,
ALTER COLUMN "beers" SET DATA TYPE DOUBLE PRECISION;
